services:
  - name: lighthouse-backend
    type: web
    runtime: docker
    repo: https://github.com/sekharraj885/Light_house_JAVA
    region: oregon
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://lighthouse:BvEbCH327l9PzmPhSV9l7ahVBDkfZvhQ@dpg-curuk623esus73fgr6qg-a/lighthouse_27s6
      - key: JWT_SECRET
        value: MySuperSecretKeyForJWT1234567890123456
    autoDeploy: true
